#!/usr/bin/env bash
# Mostra o uso de CPU em porcentagem

cpu1=($(grep '^cpu ' /proc/stat))
idle1=${cpu1[4]}
total1=0
for val in "${cpu1[@]:1}"; do total1=$((total1 + val)); done

sleep 1

cpu2=($(grep '^cpu ' /proc/stat))
idle2=${cpu2[4]}
total2=0
for val in "${cpu2[@]:1}"; do total2=$((total2 + val)); done

diff_idle=$((idle2 - idle1))
diff_total=$((total2 - total1))
diff_usage=$((100 * (diff_total - diff_idle) / diff_total))

echo "CPU: ${diff_usage}%"
 
