#!/usr/bin/env bash
# Mostra o uso de memória (em GB e %)

mem_info=$(grep Mem /proc/meminfo)
mem_total=$(echo "$mem_info" | awk '/MemTotal/ {print $2}')
mem_avail=$(echo "$mem_info" | awk '/MemAvailable/ {print $2}')
mem_used=$((mem_total - mem_avail))
mem_perc=$((100 * mem_used / mem_total))

mem_used_gb=$(awk "BEGIN {printf \"%.1f\", $mem_used / 1024 / 1024}")
mem_total_gb=$(awk "BEGIN {printf \"%.1f\", $mem_total / 1024 / 1024}")

echo "RAM: ${mem_perc}% (${mem_used_gb}G / ${mem_total_gb}G)"
